version: '3.5'
services:
  maven:
    build: ./mvn
    volumes:
      - app:/webapps

  tomcat:
    build: ./tom
    image: mytomcat
    ports:
      - "8888:8080"
    volumes:
      - app:/opt/tomcat/webapps
volumes:
  app:

