FROM maven:3.6.3-openjdk-8-slim
RUN apt update && apt install git  -y && mkdir /webapps
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /opt/git/boxfuse-sample-java-war-hello/
RUN mvn clean package -f /opt/git/boxfuse-sample-java-war-hello/pom.xml
RUN cp /opt/git/boxfuse-sample-java-war-hello/target/*.war  /webapps/test.war